version: '3'
services:
  postgresdb:
    container_name: postgresdb
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@local.de}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/serverconf/servers.json
    ports:
      - ${PGADMIN_PORT:-9000}:80
    volumes:
      - ${PGADMIN_CONFIG_FILE:-pgadmin4}:/pgadmin4/serverconf/servers.json
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:

